name: 'Zephyr West Actions'
description: 'Perform West actions to initialize/update/build a zephyr out-of-tree module'

inputs:
  manifestdir:
    description: >
      Directory where out-of-tree zephyr module containing a West manifest has
      been checked out.
    required: True

  init:
    description: >
      When set to true, initialiaze West Workplace, based on manifestdir
      specified in user's workflow.
    required: false
    default: false

  update:
    description: 'When set to true, update repository based on manifest'
    required: false
    default: false

  update_extra_args:
    description: 'When defined, must contains space separated list of modules to update'
    requried: false

  twister:
    description: >
      When set to true, runs twister test suite on directory specified in
      twister_app_dir with board defined in twister_board.
    required: false
    default: false

  twister_app_dir:
    description: >
      Mandatory when twister is set to true.
      This variable must contains a path to the application that will be built
      by twister.
    required: false

  twister_board:
    description: >
      Mandatory when twister is set to true.
      This variable must contains the name of the board that twister will compile for.
    required: false

  twister_board_root:
    description: >
      Directory to search for board configuration files and passed to twister
      option --board-root.
    required: false

  twister_build_dir:
    description: >
      Output directory for twister.
    required: false

  twister_extra_args:
    description: >
      Extra arguments directly passed to twister
    reuiqred: false

  build:
    description: >
      When set to true, runs west build on directory specified in build_app_dir
      with board defined in build_board.
    required: false
    default: false

  build_board:
    description: >
      Mandatory when build is set to true.
      This variable must contains the name of the board that west will compile for.
    required: false

  build_app_dir:
    description: >
      Mandatory when build is set to true.
      This variable must contains a path to the application that will be built
      by west.
    required: false

  build_dir:
    description: >
      Directory where built files are placed.
    required: false

  cmake_extra_args:
    description: >
      arguments passed directly to cmake by west command.
    required: false

  sign:
    description: >
      When set to true, sign the apps provided in the signing manifest.
    required: false
    default: false

  sign_manifest:
    description: >
      Mandatory when sign is set to true.
      Path to file containing the applications to sign and their respective version.
      On each line of the file there should be first the application directory
      and the version separated by a ';'
    required: false

  sign_key:
    description: >
      Path to signing key.
    required: false
    default: bootloader/mcuboot/root-rsa-2048.pem

  sign_alignment:
    description: >
      Flash alignement in bytes.
    required: false
    default: 32

runs:
  using: 'docker'
  image: 'docker://ghcr.io/siemaapplications/zephyr-action:v3.0.1'
  entrypoint: '/entrypoint.sh'
  post-entrypoint: '/cleanup.sh'
